"""
sindy_baseline.py
-----------------
Runs the SINDy baseline on the Lorenz-96 data generated by lorenz96.py.

SINDy (Sparse Identification of Nonlinear Dynamics) attempts to recover
the governing equations by finding a sparse set of basis functions from
a candidate library that best explains the observed time derivatives.

This is Baseline B2 in the SymFM paper.
We run it at N=4, 10, 20, 40 and record:
  - Equation Recovery Rate (ERR)
  - Relative L2 error
  - Symbolic complexity (number of terms)
  - Runtime

Author: Edmund Eric Gah
Project: SymFM
"""

import numpy as np
import pysindy as ps
import time
import os
import json
import warnings
warnings.filterwarnings("ignore")


# ── Helper: load data ─────────────────────────────────────────────────────────

def load_data(N, data_dir="data"):
    path = os.path.join(data_dir, f"lorenz96_N{N}.npz")
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Data file not found: {path}\n"
            f"Please run lorenz96.py first."
        )
    d = np.load(path)
    return {
        'X':     d['X'],
        'dXdt':  d['dXdt'],
        't':     d['t'],
        'N':     int(d['N']),
        'F':     float(d['F'])
    }


# ── Helper: check equation recovery ──────────────────────────────────────────

def check_equation_recovery(model, N, F=8.0, tol=0.05):
    """
    Checks whether SINDy recovered the correct Lorenz-96 equation.
    """
    try:
        coefs = model.coefficients()
        feature_names = model.get_feature_names()
    except Exception as e:
        return False, {"error": str(e)}

    details = {}
    all_recovered = True

    for i in range(N):
        row = coefs[i]

        linear_key = f"x{i}"
        linear_idx = None
        for j, name in enumerate(feature_names):
            if name == linear_key:
                linear_idx = j
                break

        if linear_idx is None:
            all_recovered = False
            details[f"var_{i}"] = "linear term not found"
            continue

        linear_coef = row[linear_idx]
        linear_ok = abs(linear_coef - (-1.0)) / 1.0 < tol

        const_idx = None
        for j, name in enumerate(feature_names):
            if name == "1":
                const_idx = j
                break

        const_ok = True
        if const_idx is not None:
            const_coef = row[const_idx]
            const_ok = abs(const_coef - F) / F < tol

        var_recovered = linear_ok and const_ok
        if not var_recovered:
            all_recovered = False

        details[f"var_{i}"] = {
            "linear_coef": float(linear_coef),
            "linear_ok": linear_ok,
            "const_ok": const_ok,
            "recovered": var_recovered
        }

    return all_recovered, details


# ── Helper: compute relative L2 error ────────────────────────────────────────

def relative_l2_error(x_true, x_pred):
    num = np.linalg.norm(x_true - x_pred)
    den = np.linalg.norm(x_true)
    if den < 1e-10:
        return float('inf')
    return float(num / den)


# ── Main SINDy experiment ─────────────────────────────────────────────────────

def run_sindy_baseline(N, data_dir="data", results_dir="results", n_trials=10):
    """
    Runs SINDy on the Lorenz-96 data at state dimension N.
    """
    print(f"\n{'='*60}")
    print(f"SINDy Baseline: Lorenz-96 N={N}")
    print(f"{'='*60}")

    data = load_data(N, data_dir)
    X_all    = data['X']
    dXdt_all = data['dXdt']
    t        = data['t']
    F        = data['F']
    dt       = float(t[1] - t[0])
    n_traj   = X_all.shape[0]

    print(f"Loaded {n_traj} trajectories, {X_all.shape[1]} timesteps, dt={dt}")
    print(f"Running {n_trials} independent trials...")

    err_rates    = []
    l2_errors    = []
    complexities = []
    runtimes     = []

    T      = X_all.shape[1]
    T_fit  = int(0.8 * T)
    T_test = T - T_fit

    for trial in range(n_trials):
        traj_idx = trial % n_traj

        X_fit    = X_all[traj_idx, :T_fit, :]
        dXdt_fit = dXdt_all[traj_idx, :T_fit, :]
        X_test   = X_all[traj_idx, T_fit:, :]
        t_fit    = t[:T_fit]
        t_test   = t[T_fit:]

        # Use simpler library for high dimensions to avoid timeout
        if N >= 20:
            library = ps.PolynomialLibrary(degree=1, include_interaction=False)
        else:
            library = ps.PolynomialLibrary(degree=2, include_interaction=True)

        model = ps.SINDy(
            feature_library=library,
            optimizer=ps.STLSQ(threshold=0.05, alpha=0.05),
        )

        start_time = time.time()
        try:
            model.fit(X_fit, t=dt, x_dot=dXdt_fit)
            runtime = time.time() - start_time

            recovered, details = check_equation_recovery(model, N, F=F)
            err_rates.append(1.0 if recovered else 0.0)

            coefs = model.coefficients()
            complexity = int(np.sum(np.abs(coefs) > 1e-4))
            complexities.append(complexity)

            try:
                x0_test = X_test[0]
                x_pred  = model.simulate(x0_test, t_test)
                l2 = relative_l2_error(X_test, x_pred)
                l2_errors.append(min(l2, 10.0))
            except Exception:
                l2_errors.append(10.0)

            runtimes.append(runtime)

            status = "RECOVERED" if recovered else "failed"
            print(f"  Trial {trial+1:2d}/{n_trials}: {status} | "
                  f"L2={l2_errors[-1]:.4f} | "
                  f"complexity={complexity} | "
                  f"time={runtime:.2f}s")

        except Exception as e:
            print(f"  Trial {trial+1:2d}/{n_trials}: ERROR -- {e}")
            err_rates.append(0.0)
            l2_errors.append(10.0)
            complexities.append(0)
            runtimes.append(0.0)

    results = {
        "method":          "SINDy",
        "N":               N,
        "F":               F,
        "n_trials":        n_trials,
        "ERR_mean":        float(np.mean(err_rates) * 100),
        "ERR_std":         float(np.std(err_rates)  * 100),
        "L2_mean":         float(np.mean(l2_errors)),
        "L2_std":          float(np.std(l2_errors)),
        "complexity_mean": float(np.mean(complexities)),
        "runtime_mean_s":  float(np.mean(runtimes)),
        "per_trial": {
            "err_rates":    [float(x) for x in err_rates],
            "l2_errors":    [float(x) for x in l2_errors],
            "complexities": [int(x)   for x in complexities],
            "runtimes":     [float(x) for x in runtimes],
        }
    }

    print(f"\n{'─'*50}")
    print(f"SINDy Results: N={N}")
    print(f"{'─'*50}")
    print(f"  Equation Recovery Rate: {results['ERR_mean']:.1f}% "
          f"(+/- {results['ERR_std']:.1f}%)")
    print(f"  Relative L2 Error:      {results['L2_mean']:.4f} "
          f"(+/- {results['L2_std']:.4f})")
    print(f"  Symbolic Complexity:    {results['complexity_mean']:.1f} terms (mean)")
    print(f"  Mean Runtime:           {results['runtime_mean_s']:.3f} s")

    os.makedirs(results_dir, exist_ok=True)
    save_path = os.path.join(results_dir, f"sindy_N{N}.json")
    with open(save_path, "w") as f:
        json.dump(results, f, indent=2)
    print(f"\n  Results saved to: {save_path}")

    return results


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    print("=" * 60)
    print("SymFM Phase 2: SINDy Baseline at N=20 and N=40")
    print("=" * 60)

    all_results = {}

    for N in [20, 40]:
        results = run_sindy_baseline(
            N=N,
            data_dir="data",
            results_dir="results",
            n_trials=3
        )
        all_results[f"N{N}"] = results

    print(f"\n{'='*60}")
    print("SINDY BASELINE SUMMARY (N=20 and N=40)")
    print(f"{'='*60}")
    print(f"{'N':<6} {'ERR (%)':<12} {'L2 Error':<12} {'Complexity':<12} {'Time (s)'}")
    print(f"{'─'*55}")
    for key, res in all_results.items():
        print(f"{res['N']:<6} "
              f"{res['ERR_mean']:<12.1f} "
              f"{res['L2_mean']:<12.4f} "
              f"{res['complexity_mean']:<12.1f} "
              f"{res['runtime_mean_s']:.3f}")

    print(f"\nAll results saved in results/ folder.")
    print("Next step: run kan_baseline.py for N=20 and N=40")